name: Compile latex

on: [push, pull_request, workflow_dispatch]

jobs:
  compile:
    runs-on: ubuntu-latest
    env:
      location_latex: "latex_files"
    steps:
    - uses: actions/checkout@v2
    - name: Install latex
      run: sudo apt-get install -yq texlive texlive-latex-extra
    - name: Install extra package need
      run: sudo apt-get install -yq texlive-science
    
    - name: Compile Chapitre 1
      uses: ./.github/actions/action_compile
      with:
        document_tex: "compilation_chapitre1.tex"
        location_file: ${{ env.location_latex }}
        
    - name: Compile these doc
      uses: ./.github/actions/action_compile
      with:
        document_tex: "compilation_these.tex"
        location_file: ${{ env.location_latex }}
    
    - name: Compile Full document
      uses: ./.github/actions/action_compile
      with:
        document_tex: "compilation_these_avec_page_de_garde_et_abstract.tex"
        location_file: ${{ env.location_latex }}
          
    - name: Move examples
      run: |
        cp latex_files/compilation_chapitre1.pdf examples/explanations_packages.pdf
        cp latex_files/compilation_these_avec_page_de_garde_et_abstract.pdf examples/complete_thesis.pdf
        
    - name: Pull modif
      run: git pull
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Compile latex
        branch: autom
        file_pattern: ${{ env.location_latex }}/*.pdf examples
        push_options: '--force'
